openapi: 3.2.0
info:
  title: Webjet Report API
  version: 4.15.0
  description: 'Operations tagged Report across 4 of this provider''s published API definitions: webjet-tripninja-farestructure-report-book-openapi.yml, webjet-tripninja-farestructure-report-cancel-openapi.yml, webjet-tripninja-smartflights-report-book-openapi.yml, webjet-tripninja-smartflights-report-cancel-openapi.yml. Each path carries the servers of the definition it was published in.'
servers:
- url: https://sandbox.tripninja.io
  description: Sandbox server
tags:
- name: Report
paths:
  /v2/report/book/:
    post:
      summary: Booking Report
      description: ''
      operationId: ''
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookingReportRequest'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
        '400':
          description: Invalid Input
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: Error code; value is 0 for success response
                    example: IE23
                  message:
                    type: string
                    description: Contains the error message
                    example: Not a valid search
              examples:
                IE45ErrorCode:
                  $ref: '#/components/examples/IE45ErrorCode'
                IE52ErrorCode:
                  $ref: '#/components/examples/IE52ErrorCode'
                IE55ErrorCode:
                  $ref: '#/components/examples/IE55ErrorCode'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: Error code; value is 0 for success response
                    example: IE44
                  message:
                    type: string
                    description: Contains the error message
                    example: User is not authorized
      tags:
      - Report
    servers:
    - url: https://sandbox.tripninja.io
      description: Sandbox server
  /v2/report/cancel/:
    post:
      summary: Cancel Booking Report
      description: ''
      operationId: ''
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CancelRequest'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: Trip has been cancelled.
        '400':
          description: Invalid Input
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: Error code; value is 0 for success response
                    example: IE23
                  message:
                    type: string
                    description: Contains the error message
                    example: Not a valid search
              examples:
                IE52ErrorCode:
                  $ref: '#/components/examples/IE52ErrorCode'
                IE41ErrorCode:
                  $ref: '#/components/examples/IE41ErrorCode'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: Error code; value is 0 for success response
                    example: IE44
                  message:
                    type: string
                    description: Contains the error message
                    example: User is not authorized
      tags:
      - Report
    servers:
    - url: https://sandbox.tripninja.io
      description: Sandbox server
  /v3/report/book/:
    post:
      summary: Booking Report
      description: ''
      operationId: ''
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookingReportRequest_2'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: number
                    description: Status code indicating request outcome.
                    example: 200
                  message:
                    type: string
                    example: success
                    description: A human-readable message providing more details. (e.g., <code>"success"</code>)
        '400':
          description: Invalid Input
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: A human-readable error code. (e.g., <code>"IE52"</code>)
                    example: IE52
                  message:
                    type: string
                    description: A human-readable message providing more details. (e.g., <code>"Trip ID not found"</code>)
                    example: Trip ID not found
              examples:
                IE45ErrorCode:
                  $ref: '#/components/examples/IE45ErrorCode'
                IE52ErrorCode:
                  $ref: '#/components/examples/IE52ErrorCode'
                IE55ErrorCode:
                  $ref: '#/components/examples/IE55ErrorCode'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: A human-readable error code. (e.g., <code>"IE44"</code>)
                    example: IE44
                  message:
                    type: string
                    description: A human-readable message providing more details. (e.g., <code>"User is not authorized"</code>)
                    example: User is not authorized
      tags:
      - Report
    servers:
    - url: https://sandbox.tripninja.io
      description: Sandbox server
  /v3/report/cancel/:
    post:
      summary: Cancel Booking Report
      description: ''
      operationId: ''
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CancelRequest_2'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: number
                    description: Status code indicating request outcome.
                    example: 200
                  message:
                    type: string
                    description: A human-readable message providing more details. (e.g., <code>"Trip has been cancelled."</code>)
                    example: Trip has been cancelled.
        '400':
          description: Invalid Input
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: A human-readable error code. (e.g., <code>"IE13"</code>)
                    example: IE23
                  message:
                    type: string
                    description: A human-readable message providing more details. (e.g., <code>"Currency is required"</code>)
                    example: Not a valid search
              examples:
                IE52ErrorCode:
                  $ref: '#/components/examples/IE52ErrorCode'
                IE41ErrorCode:
                  $ref: '#/components/examples/IE41ErrorCode'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: A human-readable error code. (e.g., <code>"IE13"</code>)
                    example: IE44
                  message:
                    type: string
                    description: A human-readable message providing more details. (e.g., <code>"User is not authorized"</code>)
                    example: User is not authorized
      tags:
      - Report
    servers:
    - url: https://sandbox.tripninja.io
      description: Sandbox server
components:
  examples:
    IE55ErrorCode:
      summary: Reporting Data Validation Error
      value:
        status: IE55
        message: One of pricing_solution_ids or itinerary_id is required.
    IE52ErrorCode:
      summary: Trip ID Validation Error
      value:
        status: IE52
        message: Trip ID not found
    IE45ErrorCode:
      summary: customer_booking_reference_id Validation Error
      value:
        status: IE45
        message: '`customer_booking_reference_id` length is invalid (must be less than 255 characters)'
    IE41ErrorCode:
      summary: Invalid Itinerary Status Validation Error
      value:
        status: IE41
        message: Invalid itinerary status, you cannot set a cancelled itinerary to a cancelled itinerary. Make sure you are following the workflow stated in documentation. If error continues to occur, please contact support@tripninja.io
  schemas:
    BookingReportRequest:
      title: Booking Request
      type: object
      required:
      - trip_id
      - itinerary_id
      properties:
        trip_id:
          type: string
          description: Trip ID returned in search response
          example: gAAAAABlSXcLA0ChTKO9-iZT-sveIYqZ4tEluxEBAnSupx0rIBvx1NI4_7apGXoe8iTtZ4iytATGyURN7IGDUnWmSKXMYhQfA7DhlPOY4SidBcigPAKWH7k=
        itinerary_id:
          type: string
          description: Itinerary ID returned in search response
          example: f557310419e4c08a6ba40cc2785447970e7aea4c
        customer_booking_reference_id:
          type: string
          description: Customer booking reference ID from the client, and the limit is 255 characters long.
          example: cust-book-1234aa94d
        is_retry:
          type: boolean
          description: Optional field, set to true if this is a retry of a previously failed request.
          example: false
          default: false
        final_price:
          type: float
          description: Optional field used to record the final base price of the booked itinerary, excluding markup. Useful if the price changed after the search.
          example: 199.99
    CancelRequest:
      title: Request
      type: object
      required:
      - trip_id
      properties:
        trip_id:
          type: string
          description: Trip ID returned in search response
          example: gAAAAABlSXcLA0ChTKO9-iZT-sveIYqZ4tEluxEBAnSupx0rIBvx1NI4_7apGXoe8iTtZ4iytATGyURN7IGDUnWmSKXMYhQfA7DhlPOY4SidBcigPAKWH7k=
    BookingReportRequest_2:
      title: Booking Request
      type: object
      required:
      - trip_id
      - itinerary_id
      properties:
        trip_id:
          type: string
          description: Unique identifier from <code>get-searches</code> for this search. Used in all subsequent requests related to this trip.
          example: gAAAAABoElDHItHlqVNLp7dSOFaKmldHwk_d_5lBZIUhTMFJXmNnh-zpPbrPBCm-nZhqTQNeRgTt8e7X0KTOyg0cuLiB3s61xAYDoOWNMjWjM5Ln2wgSItqalRiymlk5PCcokfM3LAqp09u1i3bpWHxNTrT6yOEYk_hEwFxXwdQpkQroawW-hZUQAQM2M9763o2nWLt-LVgX0M-F2unSvWep7l9c5C8pcHxdKQ1GPdm6sxdkEgV30_9U_C-59CvVAcHWpontAcIh6kO6NSC-4_jJ4xQitlbxGyDxAd3PyuEWGBTVfdTGm8qeCEQG_XVvLDy5_uKOq9vY9i6STo-XB-kYSULYCGJ720gOFd3Ohpp1u5n20yg2I8I0hbc-227FWQFp_hBmpdvATvU9SIblcRxnEcGqyeR5axKjm1U-6cN8hJNGhNb_Ewdm8fbIPKsO4OJT4ZjvTFfLnDp5PU63TQy4wtCyzrCSqT8Zsn_JgqZqBwxQkAH-LVFX3P7oGHi17UtsTiSoPunSZF5liySn7jMAELBQ7z5V2oozO7i-NjSiWUV4kwaNlXKoHT3IvZ31P6r3bERa9SOsA2hA16hv9KMN04HX-qnZc0MVgROygu_l-d66yqejW_vk1RO35CFHqhuyVyy0N6s_59QVdY8kjzEvBNwKy19o0P5Z0khmYyDgqkvcLVdKqPRia2K8_gbbe2bXMxzss5IoqeyfAKObydL1Mr6qmEVhzM4-BwKCMjz_3lC8YNWzEGisNRC8hkY_yBhqJp2ZQkgIaoyzILAuPVXks4Hdwu_Y0iz6D3HmUPr0eiRv4rGGl4iUIDup18OclOyYvbCQ_5RS44nSY0MRwATX-QRdtRGoJeLr7Xb79eH8ImOwihSkVW7rITd8d_BF85P8Fx3XH2_Kg7l2p6mN382rpKvmFoas_K3phqlDLAY2X0ru34ZC5hOjK0BRwFcTNGCrgHHAwpt4zPYYCaAiuDwvcjC5UPvh_B4o_-j5oUpGjdM9QNEMg1OECaHSTZOFjC58h0yzs-fk0lgy0rLIMow4ABThn5APIzKerhOvAtr4j6arzHMqh0CVaprkL0XMQyPcrdDYZAU8nALT9rgDA-Fsde8mqz6E7_1vb_hevhJ91edjFkZBNzc0fmC4LbH6iNKPMUkL0GD8SByW4Uot7i6sS2KSyYCOpatBjvtS9ah1oWP23MwY11aY5HuX6ljwB1kO9JpcVuoWzr-Tl4exk_a8N-b5lmGuYsXaW_r4vgquq2MDdfuW7xagZTM-uapGOo-_8IlWjoV-7flUqaWdR5BqZWJAr1uniO0uP2gM8MAWN9aGTasPZi3-mJTQJz4Z_2Y2Fx72Oi6ICK8Ggxp29UY4B3KAP96ZpSLynaLJikz6dJlNHhTe7x9WxRr-CTxflW0MQAeif_DW6MD31FFYzYf1E757QyuZD3xCCs5OGcSkW6Kw6aT97ZrAWdqYQOLrDSp6pj-I-7OfR3EXiQLlIsR5eCy7_2nrjTwwtaO1l99Ax5I4q-rnb97qSs52o5tdEwchNURafUsENTHzPIRcgbxSPpSW3ke5j0LjqOlWRGTjrl81v4WKTJocMUEV8v61OtLOKuGPF8N_SUx4NbHw1Bar3NYGeLl1BV2B7G8ZBHXfplXV2aqM5PgygFSVXRf7Olr0zWLp9wn5
        itinerary_id:
          type: string
          description: Unique identifier from <code>generate-solutions</code> for the itinerary. Used in all subsequent requests related to this trip.
          example: cb89c9b9eb06abc00f7dab156c507ea1c0a4a7e7
        customer_booking_reference_id:
          type: string
          description: Optional field for the client's booking reference identifier. Maximum 255 characters.
          example: cust-book-1234aa94d
        is_retry:
          type: boolean
          description: 'Indicates if this request is retrying a previously failed booking attempt. '
          example: false
          default: false
        final_price:
          type: float
          description: Records the final base price of the booked itinerary, excluding markup. Useful when price changes occur between search and booking.
          example: 199.99
    CancelRequest_2:
      title: Request
      type: object
      required:
      - trip_id
      properties:
        trip_id:
          type: string
          description: Unique identifier from <code>get-searches</code> for this search. Used in all subsequent requests related to this trip.
          example: gAAAAABoElDHItHlqVNLp7dSOFaKmldHwk_d_5lBZIUhTMFJXmNnh-zpPbrPBCm-nZhqTQNeRgTt8e7X0KTOyg0cuLiB3s61xAYDoOWNMjWjM5Ln2wgSItqalRiymlk5PCcokfM3LAqp09u1i3bpWHxNTrT6yOEYk_hEwFxXwdQpkQroawW-hZUQAQM2M9763o2nWLt-LVgX0M-F2unSvWep7l9c5C8pcHxdKQ1GPdm6sxdkEgV30_9U_C-59CvVAcHWpontAcIh6kO6NSC-4_jJ4xQitlbxGyDxAd3PyuEWGBTVfdTGm8qeCEQG_XVvLDy5_uKOq9vY9i6STo-XB-kYSULYCGJ720gOFd3Ohpp1u5n20yg2I8I0hbc-227FWQFp_hBmpdvATvU9SIblcRxnEcGqyeR5axKjm1U-6cN8hJNGhNb_Ewdm8fbIPKsO4OJT4ZjvTFfLnDp5PU63TQy4wtCyzrCSqT8Zsn_JgqZqBwxQkAH-LVFX3P7oGHi17UtsTiSoPunSZF5liySn7jMAELBQ7z5V2oozO7i-NjSiWUV4kwaNlXKoHT3IvZ31P6r3bERa9SOsA2hA16hv9KMN04HX-qnZc0MVgROygu_l-d66yqejW_vk1RO35CFHqhuyVyy0N6s_59QVdY8kjzEvBNwKy19o0P5Z0khmYyDgqkvcLVdKqPRia2K8_gbbe2bXMxzss5IoqeyfAKObydL1Mr6qmEVhzM4-BwKCMjz_3lC8YNWzEGisNRC8hkY_yBhqJp2ZQkgIaoyzILAuPVXks4Hdwu_Y0iz6D3HmUPr0eiRv4rGGl4iUIDup18OclOyYvbCQ_5RS44nSY0MRwATX-QRdtRGoJeLr7Xb79eH8ImOwihSkVW7rITd8d_BF85P8Fx3XH2_Kg7l2p6mN382rpKvmFoas_K3phqlDLAY2X0ru34ZC5hOjK0BRwFcTNGCrgHHAwpt4zPYYCaAiuDwvcjC5UPvh_B4o_-j5oUpGjdM9QNEMg1OECaHSTZOFjC58h0yzs-fk0lgy0rLIMow4ABThn5APIzKerhOvAtr4j6arzHMqh0CVaprkL0XMQyPcrdDYZAU8nALT9rgDA-Fsde8mqz6E7_1vb_hevhJ91edjFkZBNzc0fmC4LbH6iNKPMUkL0GD8SByW4Uot7i6sS2KSyYCOpatBjvtS9ah1oWP23MwY11aY5HuX6ljwB1kO9JpcVuoWzr-Tl4exk_a8N-b5lmGuYsXaW_r4vgquq2MDdfuW7xagZTM-uapGOo-_8IlWjoV-7flUqaWdR5BqZWJAr1uniO0uP2gM8MAWN9aGTasPZi3-mJTQJz4Z_2Y2Fx72Oi6ICK8Ggxp29UY4B3KAP96ZpSLynaLJikz6dJlNHhTe7x9WxRr-CTxflW0MQAeif_DW6MD31FFYzYf1E757QyuZD3xCCs5OGcSkW6Kw6aT97ZrAWdqYQOLrDSp6pj-I-7OfR3EXiQLlIsR5eCy7_2nrjTwwtaO1l99Ax5I4q-rnb97qSs52o5tdEwchNURafUsENTHzPIRcgbxSPpSW3ke5j0LjqOlWRGTjrl81v4WKTJocMUEV8v61OtLOKuGPF8N_SUx4NbHw1Bar3NYGeLl1BV2B7G8ZBHXfplXV2aqM5PgygFSVXRf7Olr0zWLp9wn5
x-refined-from:
- webjet-tripninja-farestructure-report-book-openapi.yml
- webjet-tripninja-farestructure-report-cancel-openapi.yml
- webjet-tripninja-smartflights-report-book-openapi.yml
- webjet-tripninja-smartflights-report-cancel-openapi.yml
